---
- hosts: nodes 
  sudo: True
  vars:
    docker_registry_mount: /dev/sdd
  tasks:
  - name: Create a physical volume and volume group
    lvg: pvs={{ docker_registry_mount }} state=present vg=vg-registry

  - name: Create a logical volume
    lvol: vg=vg-registry lv=lv-registry size=100%FREE state=present

  - name: Create xfs file system
    filesystem: fstype=xfs dev=/dev/vg-registry/lv-registry 

  - name: Mount registry filesystem in fstab
    mount: name=/registry src=/dev/vg-registry/lv-registry fstype=xfs state=mounted

#  - name: install registry
#    shell: oadm registry --service-account=registry --config=/etc/origin/master/admin.kubeconfig --credentials=/etc/origin/master/openshift-registry.kubeconfig --mount-host=/mnt/registry --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' --selector="region=infra" >> /home/cloud-user/registry-output.log creates=/home/cloud-user/registry-output.log         	

  - name: chmod 777 /registry
    file: path=/registry mode=0777 state=touch

#  - name: restorecon -vR /mnt/registry
#    shell: restorecon -vR /mnt/registry
